version: "3"

tasks:
  up:
    desc: "Starts observability stack used with mcp to fetch logs"
    cmds:
      - docker compose --env-file .env -p observability -f infra/docker-compose.obs.yml up -d

  down:
    desc: "Stops observability stack used with mcp to fetch logs"
    cmds:
      - docker compose --env-file .env -p observability -f infra/docker-compose.obs.yml down
